import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 1. 基础 (General)
  // 对应 docusaurus.config.ts navbar 里的 sidebarId: 'general'
  general: [
    {
      type: 'autogenerated',
      dirName: 'general', // 扫描 docs/general 文件夹
    },
  ],

  // 2. 催眠 (Hypnosis)
  hypnosis: [
    {
      type: 'autogenerated',
      dirName: 'hypnosis',
    },
  ],

  // 3. 乳首 (Nipple)
  nipple: [
    {
      type: 'autogenerated',
      dirName: 'nipple',
    },
  ],

  // 4. 阴茎 (Penis)
  penis: [
    {
      type: 'autogenerated',
      dirName: 'penis',
    },
  ],

  // 5. 前列腺 (Prostate)
  prostate: [
    {
      type: 'autogenerated',
      dirName: 'prostate',
    },
  ],

  // 6. 潮吹 (Squirting)
  squirting: [
    {
      type: 'autogenerated',
      dirName: 'squirting',
    },
  ],
};

export default sidebars;

// sidebars.ts 只需要这样写
// export default {
//   mySidebar: [
//     {
//       type: 'autogenerated',
//       dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
//     },
//   ],
// };



// // sidebars.ts 
// import {
//   SidebarConfig,
//   SidebarItemConfig,
// } from "@docusaurus/plugin-content-docs/src/sidebars/types.js";
// import _raw from "./sidebars.json";
// import matter from "gray-matter";
// import { readFileSync } from "fs";

// interface Node {
//   name: string;
//   items: (Node | string)[];
// }

// const raw = _raw as Node[];

// const sidebars: SidebarConfig = Object.fromEntries(
//   raw.map(({ name, items }) => {
//     // 1. 顶级目录 index
//     const result: SidebarItemConfig[] = [`${name}/index`];

//     for (const item of items) {
//       if (typeof item === "string") {
//         // 2. 处理字符串类型的二级条目 (追加 /index)
//         result.push(`${name}/${item}/index`);
//       } else {
//         // 3. 处理对象类型的二级条目 (Category)
//         const path = name + "/" + item.name;
        
//         let label = item.name;
//         try {
//           const content = readFileSync(`docs/${path}/index.mdx`, "utf-8");
//           const frontMatter = matter(content).data;
//           if (frontMatter.title) {
//             label = frontMatter.title as string;
//           }
//         } catch (e) {
//           console.warn(`Warning: Could not read title for ${path}, using directory name.`);
//         }

//         result.push({
//           type: "category",
//           label,
//           link: { type: "doc", id: path + "/index" },
//           items: item.items.map((subitem) => {
//             // === 修复的核心部分 ===
//             // 无论是字符串还是对象，都需要追加 /index 以匹配 Available document ids
//             if (typeof subitem === "string") {
//               return `${path}/${subitem}/index`;
//             } else {
//               return `${path}/${subitem.name}/index`;
//             }
//           }),
//         });
//       }
//     }
//     return [name, result];
//   })
// );

// export default sidebars;