/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. 定义 "introduction" 侧边栏 (对应导航栏的“关于”)
  introduction: [
    // 指定显示哪些文件，按顺序排列
    'introduction/introduction', 
    'introduction/guideline',   
    'introduction/terms', 
    'introduction/knowledge', 
    'introduction/api',
  ],

  // 2. 定义 "development" 侧边栏 (对应导航栏的“开发”)
  development: [
    // 既然暂时不想管开发部分，我们用 autogenerated 自动扫描 development 文件夹
    // 只要 docs/development 文件夹存在，这就不会报错
    {
      type: 'autogenerated',
      dirName: 'development', 
    },
  ],
};

module.exports = sidebars;
  // ... development 部分保持不变
// };
// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // 既然现在只有一个 index.md，我们就做一个通用的侧边栏即可
//   // 之前的 introduction, development 等 ID 对应的文件夹都不存在了，必须删掉
//   tutorialSidebar: [
//     {
//       type: 'autogenerated',
//       dirName: '.', // 自动扫描 docs 根目录
//     },
//   ],
// };

// module.exports = sidebars;
// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // 对应导航栏的“关于” (introduction)
//   // 这里我暂时把它指向 'general' 文件夹，你可以改成你想要的文件夹名
//   introduction: [
//     {
//       type: 'autogenerated',
//       dirName: 'general', 
//     },
//   ],

//   // 对应导航栏的“开发” (development)
//   // 这里我暂时把它指向 'hypnosis' 文件夹 (仅作示例，请修改为实际的开发文档文件夹)
//   // 如果你想在一个侧边栏显示剩余的所有文件夹，你需要手动列出
//   development: [
//     {
//       type: 'autogenerated',
//       dirName: 'hypnosis', 
//     },
//     // 你可以继续添加其他文件夹
//     // { type: 'autogenerated', dirName: 'nipple' },
//   ],
// };

// module.exports = sidebars;

// module.exports = sidebars;
// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   introduction: [{type: 'autogenerated', dirName: 'general'}],
//   development: [{type: 'autogenerated', dirName: 'hypnosis'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['hello'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;
